version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: BBook
      MYSQL_USER: root
      MYSQL_PASSWORD:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: BBook
      MYSQL_USER: root
      MYSQL_PASSWORD:version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: BBook
      MYSQL_USER: root
      MYSQL_PASSWORD:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: BBook
      MYSQL_USER: root
      MYSQL_PASSWORD: